# 使用官方 Node.js 镜像
FROM node:22-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json (或 yarn.lock)
# 这样可以利用Docker的缓存机制，只有在依赖变化时才重新安装
COPY package*.json ./

# 安装所有依赖，包括开发依赖 (比如 nodemon)
RUN npm install

# 复制所有剩余的源代码
COPY . .

# 暴露 Fastify 默认监听的端口
EXPOSE 3000

# 使用 nodemon 启动开发服务器
CMD ["npm", "run", "dev"]